[package]
name = "engine"
version.workspace = true
edition.workspace = true

[dependencies]
producer.workspace = true
cracker.workspace = true
log.workspace = true
anyhow.workspace = true
crossbeam.workspace = true
